### ISSUE TITLE
Changing build configuration to use "checked: false" has no effect

### ISSUE THREAD

**Issue by schwa423** [flutter/atom-flutter#63]
The Atom console shows Flutter launching the app like so:

```
flutter run --checked --debug-port=16205 --start-paused --device-id HT4CWJT05144 • flutter logs
step_0/ • checked mode • debug
```

... even after I change .atom/launches/main.yaml to look like:

``` yaml
# Flutter launch configuration for lib/main.dart.
type: flutter
path: lib/main.dart

flutter:
  # Enable or disable checked mode.
  checked: false
  # Enable or disable debugging.
  debug: true
  # The starting route for the app.
  route:
  # Additional args for the flutter run command.
  args:
```
